name: Build and deploy Python app to Azure Web App - relationship

on:
  push:
    branches:
      - main
    paths:
      - Backend/Relationship/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Build inside Relationship folder
      - name: Create and start virtual environment and install dependencies
        working-directory: Backend/Relationship
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      # Upload ONLY Relationship app
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: relationship
          path: |
            Backend/Relationship
            !Backend/Relationship/antenv/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Download artifact to fixed path
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: relationship
          path: deploy

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: relationship
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7BB57B8A1B1940AB9F06976E59B38861 }}
          package: deploy
